/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnidemojava_UDPServer */

#ifndef _Included_jnidemojava_UDPServer
#define _Included_jnidemojava_UDPServer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
